/**
 * Centralized icon re-exports from lucide-react. Aliased to project naming so component
 * call sites stay stable. Tree-shaken: only the icons imported through this file are bundled.
 */

export {
  Plus as IconPlus,
  Search as IconSearch,
  Mic as IconMic,
  Square as IconStop,
  Copy as IconCopy,
  Download as IconDownload,
  Upload as IconUpload,
  Trash2 as IconTrash,
  Pencil as IconEdit,
  Check as IconCheck,
  X as IconX,
  Pin as IconPin,
  Tag as IconTag,
  Link as IconLink,
  Code2 as IconCode,
  Image as IconImage,
  File as IconFile,
  AlignLeft as IconText,
  Sun as IconSun,
  Moon as IconMoon,
  Settings as IconSettings,
  Rocket as IconRocket,
  Sparkles as IconSparkle,
  AlertTriangle as IconAlert,
  Info as IconInfo,
  Menu as IconMenu,
  GripVertical as IconDrag,
  Share2 as IconShare,
  AudioWaveform as IconVoice,
  Inbox as IconInbox,
  History as IconHistory,
  Layers as IconLayers,
  Keyboard as IconKeyboard,
  Eye as IconEye,
  EyeOff as IconEyeOff,
  ShieldAlert as IconShieldAlert,
  BookOpen as IconBook,
  ChevronDown as IconChevronDown,
  ChevronRight as IconChevronRight,
  ChevronUp as IconChevronUp,
  Wand2 as IconWand,
  CornerDownLeft as IconReturn,
  Maximize2 as IconExpand,
  Minimize2 as IconCollapse,
  Star as IconStar,
  MoreHorizontal as IconMore,
  Loader2 as IconLoader,
  ScrollText as IconScroll,
  ClipboardCopy as IconClipboardCopy,
  ClipboardCheck as IconClipboardCheck,
  Type as IconHeading,
  ArrowRight as IconArrowRight,
} from 'lucide-react';
